// <auto-generated />
using System;
using BOOKLOUD.DataAccessLayer.DataContext;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace BOOKLOUD.DataAccessLayer.Migrations
{
    [DbContext(typeof(BookCloudDbContext))]
    partial class BookCloudDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "2.2.6-servicing-10079")
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("BOOKLOUD.DataAccessLayer.Models.BookDetailsDALModel", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("BookAuthor");

                    b.Property<string>("BookDescription");

                    b.Property<string>("BookEdition");

                    b.Property<string>("BookImage");

                    b.Property<string>("BookIsbn");

                    b.Property<string>("BookName");

                    b.Property<int>("BookPrice");

                    b.Property<string>("CourseName");

                    b.Property<string>("UnitName");

                    b.Property<string>("University");

                    b.HasKey("Id");

                    b.ToTable("BookDetailsDALModel");
                });

            modelBuilder.Entity("BOOKLOUD.DataAccessLayer.Models.CourseDetailsDALModel", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("CourseName");

                    b.Property<int?>("UniversityId");

                    b.HasKey("Id");

                    b.HasIndex("UniversityId");

                    b.ToTable("Course");
                });

            modelBuilder.Entity("BOOKLOUD.DataAccessLayer.Models.UnitDetailsDALModel", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int?>("CourseId");

                    b.Property<string>("UnitCode");

                    b.Property<int?>("UnitDetailsModelId");

                    b.Property<string>("UnitName");

                    b.HasKey("Id");

                    b.HasIndex("CourseId");

                    b.HasIndex("UnitDetailsModelId");

                    b.ToTable("Unit");
                });

            modelBuilder.Entity("BOOKLOUD.DataAccessLayer.Models.UniversityDetailsDALModel", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("UniversityName");

                    b.HasKey("Id");

                    b.ToTable("University");
                });

            modelBuilder.Entity("BOOKLOUD.DataAccessLayer.Models.CourseDetailsDALModel", b =>
                {
                    b.HasOne("BOOKLOUD.DataAccessLayer.Models.UniversityDetailsDALModel", "University")
                        .WithMany("Course")
                        .HasForeignKey("UniversityId");
                });

            modelBuilder.Entity("BOOKLOUD.DataAccessLayer.Models.UnitDetailsDALModel", b =>
                {
                    b.HasOne("BOOKLOUD.DataAccessLayer.Models.CourseDetailsDALModel", "Course")
                        .WithMany("Unit")
                        .HasForeignKey("CourseId");

                    b.HasOne("BOOKLOUD.DataAccessLayer.Models.UnitDetailsDALModel")
                        .WithMany("University")
                        .HasForeignKey("UnitDetailsModelId");
                });
#pragma warning restore 612, 618
        }
    }
}
